# Cloudflare Pages configuration
name = "refuse-protocol-website"
compatibility_date = "2024-01-01"

# Build configuration
[build]
command = "npm run build"
cwd = "frontend"
watch_dir = "frontend/src"

# Build environment
[build.environment_variables]
NODE_VERSION = "18"
NPM_VERSION = "9"

# Pages configuration
[pages]
build_output_dir = "frontend/dist"

# Functions (if needed later)
[functions]
directory = "functions"

# Environment variables for production
[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"
