name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      run: cd frontend && npm ci

    - name: Run linting
      run: cd frontend && npm run lint

    - name: Run tests
      run: cd frontend && npm run test

    - name: Run build
      run: cd frontend && npm run build

    - name: Validate schemas
      run: |
        npm run validate
        echo "Schema validation completed successfully"

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: true

  protocol-validation:
    runs-on: ubuntu-latest
    needs: validate

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      run: cd frontend && npm ci

    - name: Validate protocol conformance
      run: |
        echo "🔍 Running protocol-specific validations..."

        # Check for broken entity references
        echo "Checking entity relationships..."
        node -e "
        const fs = require('fs');
        const entities = fs.readdirSync('protocol/implementations');
        console.log('Found entities:', entities.length);
        "

        # Validate JSON schemas
        echo "Validating JSON schemas..."
        cd frontend && npm run test -- --testPathPattern=schemas

        echo "✅ Protocol validation completed"

  security-check:
    runs-on: ubuntu-latest
    needs: validate

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Run security audit
      run: |
        npm audit --audit-level=high
        echo "Security audit completed"

    - name: Check for vulnerabilities
      run: |
        npm audit fix || echo "Some vulnerabilities require manual review"
        echo "Vulnerability check completed"
