name: Update Protocol Documentation

on:
  push:
    paths:
      - 'protocol/**'
      - 'frontend/scripts/generate-protocol-docs.js'
      - 'frontend/package.json'
  pull_request:
    paths:
      - 'protocol/**'
      - 'frontend/scripts/generate-protocol-docs.js'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Update Protocol Documentation

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Generate protocol documentation
        run: cd frontend && npm run build:protocol-docs

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain frontend/src/data/)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Documentation files have been updated"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No documentation changes detected"
          fi

      - name: Commit documentation changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add frontend/src/data/
          git commit -m "docs: auto-update protocol documentation

          Updated documentation from protocol changes:
          - Protocol overview with current entity/tool counts
          - Implementation guide with latest modules
          - Tool reference with all available tools
          - Schema reference with latest definitions
          - Generated at $(date -u +'%Y-%m-%d %H:%M:%S UTC')"

      - name: Push changes
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  notify-pr:
    runs-on: ubuntu-latest
    needs: update-docs
    if: github.event_name == 'pull_request' && needs.update-docs.result == 'success'
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const docsUpdated = '${{ needs.update-docs.outputs.changed }}';

            if (docsUpdated === 'true') {
              const message = `## 📚 Protocol Documentation Updated

              The protocol documentation has been automatically updated based on the changes to the \`protocol/\` directory:

              - ✅ Protocol overview with current statistics
              - ✅ Implementation guide reflecting latest modules
              - ✅ Tool reference with all available utilities
              - ✅ Schema documentation updated

              The website will automatically display the latest protocol information once these changes are merged.

              **Review the updated documentation:**
              - Visit the [Documentation page](https://refuse-protocol.org/docs) after merge
              - Check that all protocol changes are reflected
              - Verify implementation examples are current`;

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '## 📚 Protocol Documentation Status\n\nNo documentation updates were needed for these protocol changes. The existing documentation is already current.'
              });
            }
